import Footer from 'components/ui/footer'
import Nav from 'components/ui/nav'
import Head from 'next/head'
export default function Home() {
  return (
    <div >
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
